language: python

python:
  - "3.6"
  
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev
      - python-lxml

matrix:
  include:
    - python: 3.6
      env:
        VERSION="13.0" ODOO_REPO="odoo/odoo" TESTS="1" LINT_CHECK="0"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install coverage
  - LINT_CHECK="1" travis_install_nightly
  - git --git-dir=${TRAVIS_BUILD_DIR}/.git add --all

script:
  - TRAVIS_PULL_REQUEST="1" coverage run ./travis/travis_run_tests
  - coverage run --append ./travis/self_tests

after_success:
  - TESTS="1" LINT_CHECK="0" travis_after_tests_success
